# Generated by Django 5.2.7 on 2026-05-11 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerassignment',
            name='team',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
