# Generated by Django 5.2.7 on 2026-05-12 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_workerassignment_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerassignment',
            name='issue',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='reports.infrastructureissue'),
        ),
    ]
